//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDR.AdminForms.AddPublications {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class AddPublications {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTitleAr;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator5;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fuPublication;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fuThumbnail;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator3;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(AddPublications target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTitleAr() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTitleAr = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTitleAr";
            @__ctrl.MaxLength = 250;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "direction:rtl !important;");
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ID = "RequiredFieldValidator1";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ControlToValidate = "txtTitleAr";
            @__ctrl.ErrorMessage = "Please enter title in Arabic";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator5() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegularExpressionValidator5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegularExpressionValidator5";
            @__ctrl.ValidationExpression = "^[-\\u0621-\\u064A0-9 ]+$";
            @__ctrl.ControlToValidate = "txtTitleAr";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Only arabic Characters and numbers allowed.";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTitle() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtTitle = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtTitle";
            @__ctrl.MaxLength = 250;
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ID = "RequiredFieldValidator2";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ControlToValidate = "txtTitle";
            @__ctrl.ErrorMessage = "Please enter a title in English";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegularExpressionValidator1";
            @__ctrl.ValidationExpression = "^[-_a-zA-Z0-9\'., ]{0,250}$";
            @__ctrl.ControlToValidate = "txtTitle";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Only english characters and numbers allowed.";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfuPublication() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fuPublication = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fuPublication";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator3() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ID = "RequiredFieldValidator3";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ControlToValidate = "fuPublication";
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator2() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegularExpressionValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegularExpressionValidator2";
            @__ctrl.ValidationExpression = "^.*\\.([pP][dD][fF])$";
            @__ctrl.ControlToValidate = "fuPublication";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Please select a valid image file of type .pdf.";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfuThumbnail() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fuThumbnail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fuThumbnail";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator4() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ID = "RequiredFieldValidator4";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ControlToValidate = "fuThumbnail";
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator3() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegularExpressionValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegularExpressionValidator3";
            @__ctrl.ValidationExpression = "^.*\\.([jJ][pP][gG]|[jJ][pP][eE][gG]|[pP][nN][gG])$";
            @__ctrl.ControlToValidate = "fuThumbnail";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Please select a valid image file of type .png.";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSubmit";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.Text = "submit";
            @__ctrl.OnClientClick = "return validateFormat(event);";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-default");
            @__ctrl.Click -= new System.EventHandler(this.btnSubmit_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSubmit_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "cancel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-danger");
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SCDR.AdminForms.AddPublications.AddPublications @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n    <!-- Form Begins -->\r\n        " +
                        "<div class=\"form-horizontal\">\r\n  <div class=\"form-group\">\r\n    <label  class=\"co" +
                        "l-sm-3 control-label\">Title (Arabic) : </label>\r\n    <div class=\"col-sm-6\">\r\n   " +
                        "   "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtTitleAr();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div><div class=\"col-sm-3\">\r\n            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl2;
            @__ctrl2 = this.@__BuildControlRequiredFieldValidator1();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl3;
            @__ctrl3 = this.@__BuildControlRegularExpressionValidator5();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n       </div>\r\n   </div> \r\n             <div class=\"form-group\">\r\n    <label  c" +
                        "lass=\"col-sm-3 control-label\">Title (English) : </label>\r\n    <div class=\"col-sm" +
                        "-6\">\r\n      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            @__ctrl4 = this.@__BuildControltxtTitle();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div><div class=\"col-sm-3\">\r\n            "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl5;
            @__ctrl5 = this.@__BuildControlRequiredFieldValidator2();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl6;
            @__ctrl6 = this.@__BuildControlRegularExpressionValidator1();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n       </div>\r\n   </div> \r\n              <div class=\"form-group\">\r\n       <labe" +
                        "l  class=\"col-sm-3 control-label\">Select Document : </label>\r\n    <div class=\"co" +
                        "l-sm-6\">\r\n        "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl7;
            @__ctrl7 = this.@__BuildControlfuPublication();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"col-sm-3\">\r\n    <span style=\"color:red\" id=\"lblImag" +
                        "eError\"></span>\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl8;
            @__ctrl8 = this.@__BuildControlRequiredFieldValidator3();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl9;
            @__ctrl9 = this.@__BuildControlRegularExpressionValidator2();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n \r\n  </div>\r\n\r\n\r\n             <div class=\"form-group\">\r\n       <lab" +
                        "el  class=\"col-sm-3 control-label\">Select Thumbnail : </label>\r\n    <div class=\"" +
                        "col-sm-6\">\r\n        "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl10;
            @__ctrl10 = this.@__BuildControlfuThumbnail();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n    <div class=\"col-sm-3\">\r\n    <span style=\"color:red\" id=\"lblThum" +
                        "bnailError\"></span>\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl11;
            @__ctrl11 = this.@__BuildControlRequiredFieldValidator4();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl12;
            @__ctrl12 = this.@__BuildControlRegularExpressionValidator3();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n \r\n  </div>\r\n\r\n              <div class=\"form-group\">\r\n    <div cla" +
                        "ss=\"col-sm-offset-3 col-sm-9\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl13;
            @__ctrl13 = this.@__BuildControlbtnSubmit();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n             "));
            global::System.Web.UI.WebControls.Button @__ctrl14;
            @__ctrl14 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n  </div>\r\n\r\n            </div>\r\n    </div>\r\n\r\n<script>\r\n    $(docum" +
                        "ent).ready(function () {\r\n        $(\'#lblImageError\').hide();\r\n        $(\"input[" +
                        "name$=fuPublication]\").change(function () {\r\n            $(\'#lblImageError\').hid" +
                        "e();\r\n        });\r\n        $(\'#lblThumbnailError\').hide();\r\n        $(\"input[nam" +
                        "e$=fuThumbnail]\").change(function () {\r\n            $(\'#lblThumbnailError\').hide" +
                        "();\r\n        });\r\n    });\r\n</script>\r\n<script type=\"text/javascript\">\r\n    funct" +
                        "ion validateFormat(event) {\r\n        if (Page_ClientValidate()) {\r\n         \r\n  " +
                        "       //pdf checking  \r\n            var ext = $(\"input[name$=fuPublication]\").g" +
                        "et(0).files.length;\r\n            if (ext > 0) {\r\n                var names = [];" +
                        "\r\n                for (var i = 0; i < ext; ++i) {\r\n                    names.pus" +
                        "h($(\"input[name$=fuPublication]\").get(0).files[i].name);\r\n                }\r\n   " +
                        "             var x = 0;\r\n                for (i = 0; i < names.length; i++) {\r\n " +
                        "                   var str = names[i];\r\n                    //  /^[-\\sa-zA-Z]+$/" +
                        "\r\n                    if (/^[-_a-zA-Z0-9.\\u0600-\\u06FF ]+$/.test(str) == false) " +
                        "{\r\n\r\n                        x = 1;\r\n                    }\r\n                    " +
                        "if (x == 1) {\r\n                        $(\'#lblImageError\').show();\r\n            " +
                        "            $(\'#lblImageError\').text(\'Special characters except - and _ are not " +
                        "allowed in filename. Please select a valid image file of type .pdf.\');\r\n        " +
                        "                // setTimeout();\r\n                        return false;\r\n       " +
                        "                 break;\r\n                        event.preventDefault();\r\n      " +
                        "              }\r\n\r\n                }\r\n                if (x == 0) {\r\n\r\n         " +
                        "           var ext = [];\r\n                    for (i = 0; i < names.length; i++)" +
                        " {\r\n\r\n                        ext.push(names[i].substr(names[i].indexOf(\".\") + 1" +
                        ").toLowerCase());\r\n\r\n                    }\r\n                    var valid_filety" +
                        "pe = [\"pdf\",\"PDF\"];\r\n\r\n                    var i, j, result = [];\r\n             " +
                        "       for (i = 0; i < valid_filetype.length; i++) {\r\n                        fo" +
                        "r (j = 0; j < ext.length; j++) {\r\n                            if (ext[j].indexOf" +
                        "(valid_filetype[i]) != -1) {\r\n                                result.push(ext[j]" +
                        ");\r\n                            }\r\n                        }\r\n                  " +
                        "  }\r\n\r\n                    if (result.length < ext.length) {\r\n                  " +
                        "      //   break;\r\n                        $(\'#lblImageError\').show();\r\n        " +
                        "                $(\'#lblImageError\').text(\'Invalid File Found. Please select a va" +
                        "lid image file of type .pdf.\');\r\n                        // setTimeout();\r\n     " +
                        "                   return false;\r\n                        event.preventDefault()" +
                        ";\r\n                    }\r\n\r\n\r\n\r\n                }\r\n\r\n            } else {\r\n     " +
                        "          \r\n            }\r\n            // thumbnail checking\r\n            var ex" +
                        "t = $(\"input[name$=fuThumbnail]\").get(0).files.length;\r\n            if (ext > 0)" +
                        " {\r\n                var names = [];\r\n                for (var i = 0; i < ext; ++" +
                        "i) {\r\n                    names.push($(\"input[name$=fuThumbnail]\").get(0).files[" +
                        "i].name);\r\n                }\r\n                var x = 0;\r\n                for (i" +
                        " = 0; i < names.length; i++) {\r\n                    var str = names[i];\r\n       " +
                        "             //  /^[-\\sa-zA-Z]+$/\r\n                    if (/^[-_a-zA-Z0-9.\\u0600" +
                        "-\\u06FF ]+$/.test(str) == false) {\r\n\r\n                        x = 1;\r\n          " +
                        "          }\r\n                    if (x == 1) {\r\n                        $(\'#lblT" +
                        "humbnailError\').show();\r\n                        $(\'#lblThumbnailError\').text(\'S" +
                        "pecial characters except - and _ are not allowed in filename. Please select a va" +
                        "lid image file of type .png.\');\r\n                        // setTimeout();\r\n     " +
                        "                   return false;\r\n                        break;\r\n              " +
                        "          event.preventDefault();\r\n                    }\r\n\r\n                }\r\n " +
                        "               if (x == 0) {\r\n\r\n                    var ext = [];\r\n             " +
                        "       for (i = 0; i < names.length; i++) {\r\n\r\n                        ext.push(" +
                        "names[i].substr(names[i].indexOf(\".\") + 1).toLowerCase());\r\n\r\n                  " +
                        "  }\r\n                    var valid_filetype = [\"png\", \"PNG\",\"jpg\",\"JPG\",\"jpeg\",\"" +
                        "JPEG\"];\r\n\r\n                    var i, j, result = [];\r\n                    for (" +
                        "i = 0; i < valid_filetype.length; i++) {\r\n                        for (j = 0; j " +
                        "< ext.length; j++) {\r\n                            if (ext[j].indexOf(valid_filet" +
                        "ype[i]) != -1) {\r\n                                result.push(ext[j]);\r\n        " +
                        "                    }\r\n                        }\r\n                    }\r\n\r\n     " +
                        "               if (result.length < ext.length) {\r\n                        //   b" +
                        "reak;\r\n                        $(\'#lblThumbnailError\').show();\r\n                " +
                        "        $(\'#lblThumbnailError\').text(\'Invalid File Found. Please select a valid " +
                        "image file of type .png.\');\r\n                        // setTimeout();\r\n         " +
                        "               return false;\r\n                        event.preventDefault();\r\n " +
                        "                   }\r\n\r\n\r\n\r\n                }\r\n\r\n            } else {\r\n\r\n       " +
                        "     }\r\n        }\r\n    }\r\n\r\n</script>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
