//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDR.CommonLogin {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class CommonLogin {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Login signInControl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.LinkButton lbInternalUsers;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Label lblError;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.EncodedLiteral ClaimsFormsPageMessage;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(CommonLogin target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Login @__BuildControlsignInControl() {
            global::System.Web.UI.WebControls.Login @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Login();
            this.signInControl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "signInControl";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("style", "width: 250px");
            @__ctrl.FailureText = "Failed to login";
            @__ctrl.MembershipProvider = "FBAMembershipProvider";
            @__ctrl.DisplayRememberMe = true;
            @__ctrl.TextBoxStyle.Width = new System.Web.UI.WebControls.Unit(250D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.RememberMeSet = true;
            @__ctrl.LoginButtonStyle.CssClass = "ms-buttonheightwidth";
            @__ctrl.UserNameLabelText = "User name";
            @__ctrl.TextLayout = global::System.Web.UI.WebControls.LoginTextLayout.TextOnTop;
            @__ctrl.PasswordLabelText = "Password";
            @__ctrl.LabelStyle.Font.Bold = false;
            @__ctrl.LabelStyle.Font.Size = global::System.Web.UI.WebControls.FontUnit.Large;
            @__ctrl.LabelStyle.ForeColor = global::System.Drawing.Color.White;
            @__ctrl.LabelStyle.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.LabelStyle.CssClass = "ms-standardheader ms-inputformheader";
            @__ctrl.TextBoxStyle.CssClass = "ms-input";
            @__ctrl.CheckBoxStyle.Font.Bold = false;
            @__ctrl.CheckBoxStyle.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.CheckBoxStyle.ForeColor = global::System.Drawing.Color.White;
            @__ctrl.CheckBoxStyle.CssClass = "ms-standardheader ms-inputformheader";
            @__ctrl.CheckBoxStyle.Font.Size = global::System.Web.UI.WebControls.FontUnit.Large;
            @__ctrl.FailureTextStyle.Wrap = true;
            @__ctrl.FailureTextStyle.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.FailureTextStyle.Font.Size = global::System.Web.UI.WebControls.FontUnit.Small;
            @__ctrl.LoginButtonStyle.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.LoginButtonStyle.Font.Size = global::System.Web.UI.WebControls.FontUnit.Large;
            @__ctrl.LoginButtonImageUrl = "/_layouts/images/zavaz.CustomLoginPage/GoForward.png";
            @__ctrl.LoginButtonType = global::System.Web.UI.WebControls.ButtonType.Image;
            @__ctrl.TitleText = "";
            @__ctrl.TitleTextStyle.ForeColor = global::System.Drawing.Color.White;
            @__ctrl.TitleTextStyle.Font.Bold = true;
            @__ctrl.TitleTextStyle.Wrap = true;
            @__ctrl.TitleTextStyle.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.TitleTextStyle.Font.Size = global::System.Web.UI.WebControls.FontUnit.Larger;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllbInternalUsers() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lbInternalUsers = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lbInternalUsers";
            @__ctrl.Text = "Active Directory Login";
            @__ctrl.Font.Names = new string[] {
                    "Calibri"};
            @__ctrl.Font.Size = global::System.Web.UI.WebControls.FontUnit.Small;
            @__ctrl.CssClass = "ms-standardheader ms-inputformheader";
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = global::System.Drawing.Color.Wheat;
            @__ctrl.Click -= new System.EventHandler(this.lbInternalUsers_OnClick);
            @__ctrl.Click += new System.EventHandler(this.lbInternalUsers_OnClick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblError";
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.EnableViewState = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.EncodedLiteral @__BuildControlClaimsFormsPageMessage() {
            global::Microsoft.SharePoint.WebControls.EncodedLiteral @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.EncodedLiteral();
            this.ClaimsFormsPageMessage = @__ctrl;
            @__ctrl.EncodeMethod = global::Microsoft.SharePoint.WebControls.SPEncodeMethod.HtmlEncode;
            @__ctrl.ID = "ClaimsFormsPageMessage";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SCDR.CommonLogin.CommonLogin @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<
 
 <script language=""javascript"" type=""text/javascript"" >
 
 $(document).ready(function () {
 //Hidding unnecessary elements from masterpage
 $('#s4-simple-card').attr(""id"", ""s4-simple-card2"");
 $('#s4-simple-header').hide();
 $('#s4-simple-card-top').hide();
 $('#s4-simple-card-content').css(""margin"", ""0px"");
 $('.s4-simple-iconcont').hide();
 $('#s4-simple-content').css(""margin"", ""0px"");
 $('#s4-simple-content h1:first').hide();
 $('.s4-die').hide();
 //-------------------
 
 //Round corners of the div
 $('.rounded').corner(""10px"");
 });
 </script>
 
 <style type=""text/css"">
 
 html, body {height:100%; margin:0; padding:0;}
 
 #page-background {position:fixed; top:0; left:0; width:100%; height:100%;}
 
 #content {position:relative; z-index:1; padding:10px;}
 
 </style>

<div style=""background-color: Black; width: 100%; height: 100px"">
 <br />
 <img src='/_layouts/images/zavaz.CustomLoginPage/Logo.png' alt='' />
 </div>
 <div style=""background-color: Gray; width: 100%; height: 10px""></div>
 <center>
 <div id=""content"" class=""rounded"" style=""width: 300px; height: auto; margin-top: 15%; background:transparent; filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000,endColorstr=#99000000); zoom: 1;"">
 
 //Standard Login control with set custom MembershipProvider FBAMembershipProvider
 "));
            global::System.Web.UI.WebControls.Login @__ctrl1;
            @__ctrl1 = this.@__BuildControlsignInControl();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \r\n //Link for internal users to log in using AD account\r\n "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl2;
            @__ctrl2 = this.@__BuildControllbInternalUsers();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \r\n //Label displaying errors\r\n "));
            global::System.Web.UI.WebControls.Label @__ctrl3;
            @__ctrl3 = this.@__BuildControllblError();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n </div>\r\n </center>\r\n \r\n //Required from inherited class \"FormsSignInPage\"\r\n "));
            global::Microsoft.SharePoint.WebControls.EncodedLiteral @__ctrl4;
            @__ctrl4 = this.@__BuildControlClaimsFormsPageMessage();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
