//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCDR.AdminForms.EditCalendarEvents {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EditCalendarEvents {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventName;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator req1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegExp1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlEventVenue;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventDate;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventStartTime;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventEndTime;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.TextBox txtEventDescription;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Image imgEvent;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fuEventImage;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EditCalendarEvents target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventName";
            @__ctrl.MaxLength = 250;
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlreq1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.req1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ControlToValidate = "txtEventName";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "req1";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Please enter event name";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegExp1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegExp1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegExp1";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ValidationExpression = "^[-_a-zA-Z0-9\\u0600-\\u06FF\'., ]{0,250}$";
            @__ctrl.ControlToValidate = "txtEventName";
            @__ctrl.ErrorMessage = "Maximum 250 characters allowed.Special characters except \' . _ - , are not allowe" +
                "d";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlEventVenue() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlEventVenue = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CausesValidation = true;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "ddlEventVenue";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.InitialValue = "0";
            @__ctrl.ControlToValidate = "ddlEventVenue";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator1";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Please select a Venue";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventDate = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventDate";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ControlToValidate = "txtEventDate";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator2";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventStartTime() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventStartTime = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventStartTime";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventEndTime() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventEndTime = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventEndTime";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator5() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ControlToValidate = "txtEventStartTime";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator5";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator6() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator6 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            @__ctrl.ControlToValidate = "txtEventEndTime";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator6";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtEventDescription() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            this.txtEventDescription = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "txtEventDescription";
            @__ctrl.ClientIDMode = global::System.Web.UI.ClientIDMode.Static;
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator4() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ControlToValidate = "txtEventDescription";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator4";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlDepartment() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlDepartment = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.CausesValidation = true;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            @__ctrl.ID = "ddlDepartment";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator7() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            this.RequiredFieldValidator7 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.InitialValue = "0";
            @__ctrl.ControlToValidate = "ddlDepartment";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.ID = "RequiredFieldValidator7";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Required Field";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Image @__BuildControlimgEvent() {
            global::System.Web.UI.WebControls.Image @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Image();
            this.imgEvent = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "imgEvent";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfuEventImage() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fuEventImage = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fuEventImage";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("accept", "image/jpeg,image/jpg,image/png,image/JPEG,image/PNG,image/JPG");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "RegularExpressionValidator1";
            @__ctrl.ValidationExpression = "^.*\\.([jJ][pP][gG]|[jJ][pP][eE][gG]|[pP][nN][gG])$";
            @__ctrl.ControlToValidate = "fuEventImage";
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            @__ctrl.ErrorMessage = "Please select a valid image file of type .jpg,.jpeg,.png.";
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSubmit";
            @__ctrl.ValidationGroup = "chk";
            @__ctrl.Text = "submit";
            @__ctrl.OnClientClick = "return validateFormat(event);";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-default");
            @__ctrl.Click -= new System.EventHandler(this.btnSubmit_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSubmit_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "cancel";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "btn btn-danger");
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SCDR.AdminForms.EditCalendarEvents.EditCalendarEvents @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
<!-- Include Bootstrap Datepicker -->
        <link rel=""stylesheet"" href=""../../_layouts/15/SCDR/css/datepicker.min.css"" />
        <link rel=""stylesheet"" href=""../../_layouts/15/SCDR/css/datepicker3.min.css"" />
<link href=""../../_layouts/15/SCDR/css/bootstrap-datetimepicker.css"" rel=""stylesheet"" />
<div class=""col-md-12 col-sm-12 col-xs-12"">
        <!-- Form Begins -->
        <div class=""form-horizontal"">
            
       <div class=""form-group"">
    <label  class=""col-sm-3 control-label"">Event Name : </label>
    <div class=""col-sm-6"">
      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            @__ctrl1 = this.@__BuildControltxtEventName();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div>\r\n      <div class=\"col-sm-3\">\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl2;
            @__ctrl2 = this.@__BuildControlreq1();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n     "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl3;
            @__ctrl3 = this.@__BuildControlRegExp1();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            </div>\r\n  </div>\r\n            <div class=\"form-group\">\r\n    <label " +
                        " class=\"col-sm-3 control-label\">Event Venue : </label>\r\n    <div class=\"col-sm-6" +
                        "\">\r\n        "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            @__ctrl4 = this.@__BuildControlddlEventVenue();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    \r\n  </div>\r\n        <div class=\"col-sm-3\">\r\n         "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl5;
            @__ctrl5 = this.@__BuildControlRequiredFieldValidator1();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n  </div>\r\n       \r\n            <div class=\"form-group\">\r\n    <lab" +
                        "el  class=\"col-sm-3 control-label\">Event Date : </label>\r\n    <div class=\"col-sm" +
                        "-6\">\r\n      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            @__ctrl6 = this.@__BuildControltxtEventDate();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div>\r\n          <div class=\"col-sm-3\">\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl7;
            @__ctrl7 = this.@__BuildControlRequiredFieldValidator2();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n  </div>\r\n            \r\n       <div class=\"form-group\">\r\n    <lab" +
                        "el  class=\"col-sm-3 control-label\">Event Time : </label>\r\n \r\n         <div class" +
                        "=\"col-sm-2\">\r\n                  "));
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            @__ctrl8 = this.@__BuildControltxtEventStartTime();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n             </div>\r\n           <div class=\"col-sm-2\">\r\n               <center>" +
                        "\r\n                <label  class=\"control-label\">to </label></center>\r\n          " +
                        "     </div>\r\n         <div class=\"col-sm-2\">\r\n      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            @__ctrl9 = this.@__BuildControltxtEventEndTime();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n             </div>\r\n                  <div class=\"col-sm-3\">\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            @__ctrl10 = this.@__BuildControlRequiredFieldValidator5();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n           "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl11;
            @__ctrl11 = this.@__BuildControlRequiredFieldValidator6();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n \r\n  </div>\r\n\r\n            <div class=\"form-group\">\r\n    <label  " +
                        "class=\"col-sm-3 control-label\">Event Description : </label>\r\n    <div class=\"col" +
                        "-sm-6\">\r\n      "));
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            @__ctrl12 = this.@__BuildControltxtEventDescription();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div>\r\n         <div class=\"col-sm-3\">\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl13;
            @__ctrl13 = this.@__BuildControlRequiredFieldValidator4();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n  </div>\r\n\r\n            <div class=\"form-group\">\r\n    <label  cla" +
                        "ss=\"col-sm-3 control-label\">Department : </label>\r\n    <div class=\"col-sm-6\">\r\n " +
                        "     "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl14;
            @__ctrl14 = this.@__BuildControlddlDepartment();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n  </div>\r\n                 <div class=\"col-sm-3\">\r\n          "));
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl15;
            @__ctrl15 = this.@__BuildControlRequiredFieldValidator7();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n      </div>\r\n  </div>\r\n\r\n               \r\n                 <div class=\"form-gr" +
                        "oup\">\r\n    <label  class=\"col-sm-3 control-label\">Saved Image : </label>\r\n    <d" +
                        "iv class=\"col-sm-6\">\r\n    "));
            global::System.Web.UI.WebControls.Image @__ctrl16;
            @__ctrl16 = this.@__BuildControlimgEvent();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@" </div>
                 <div class=""col-sm-3"">
             </div>
  </div>
                  <div class=""form-group"">
                         <label  class=""col-sm-3 control-label"">Do you want to update current image? : </label>
   <div class=""col-sm-9"">
    <label><input id=""chkYes"" type=""radio"" name=""chkImage"" value=""Yes""> Yes</label>
    <label><input id=""chkNo"" type=""radio"" checked=""checked"" name=""chkImage"" value=""No""> No</label>
       </div>
                      </div>
 <div class=""form-group"" id=""divEventPicture"">
    <label class=""col-sm-3 control-label"">Choose an Image:</label>
      <div class=""col-sm-6"">
     "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl17;
            @__ctrl17 = this.@__BuildControlfuEventImage();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n          </div>\r\n     <div class=\"col-md-3\">\r\n            <span style=\"color:r" +
                        "ed\" id=\"lblImageError\"></span>\r\n           "));
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl18;
            @__ctrl18 = this.@__BuildControlRegularExpressionValidator1();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n     </div>\r\n  </div>\r\n                <div class=\"form-group\">\r\n    <div class" +
                        "=\"col-sm-offset-3 col-sm-9\">\r\n        "));
            global::System.Web.UI.WebControls.Button @__ctrl19;
            @__ctrl19 = this.@__BuildControlbtnSubmit();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n             "));
            global::System.Web.UI.WebControls.Button @__ctrl20;
            @__ctrl20 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div>\r\n  </div>\r\n                   \r\n         \r\n    \r\n            </div>\r" +
                        "\n    <!-- Form Ends -->\r\n    </div>\r\n <!-- datetime picker script-->\r\n<script ty" +
                        "pe=\"text/javascript\" src=\"../../_layouts/15/SCDR/js/moment.js\"></script>\r\n<scrip" +
                        "t type=\"text/javascript\" src=\"../../_layouts/15/SCDR/js/bootstrap-datepicker.min" +
                        ".js\" ></script>\r\n<script type=\"text/javascript\" src=\"../../_layouts/15/SCDR/js/b" +
                        "ootstrap-datetimepicker.js\"></script>\r\n\r\n   <script type=\"text/javascript\">\r\n   " +
                        "    $(document).ready(function () {\r\n           $(\'#txtEventDate\')\r\n            " +
                        "   .datepicker({\r\n                   format: \'dd/MM/yyyy\',\r\n                   t" +
                        "odayHighlight: true\r\n               });\r\n\r\n                       $(\'#txtEventSt" +
                        "artTime\').datetimepicker({\r\n                           format: \'LT\'\r\n           " +
                        "            });\r\n                       $(\'#txtEventEndTime\').datetimepicker({\r\n" +
                        "                           format: \'LT\'\r\n                       });\r\n           " +
                        "            $(\"#divEventPicture\").hide();\r\n                       $(\"input[name=" +
                        "\'chkImage\']\").click(function () {\r\n                           if ($(\"#chkYes\").i" +
                        "s(\":checked\")) {\r\n                               $(\"#divEventPicture\").show();\r\n" +
                        "                           } else {\r\n                               $(\"#divEvent" +
                        "Picture\").hide();\r\n                           }\r\n                       });\r\n\r\n " +
                        "           \r\n       });\r\n    </script>\r\n\r\n<!--fileupload Script-->\r\n<script>\r\n  " +
                        "  $(document).ready(function () {\r\n        $(\'#lblImageError\').hide();\r\n        " +
                        "$(\"input[name$=fuEventImage]\").change(function () {\r\n            $(\'#lblImageErr" +
                        "or\').hide();\r\n        });\r\n\r\n\r\n    });\r\n</script>\r\n\r\n<!--fileupload Script-->\r\n<" +
                        "script type=\"text/javascript\">\r\n    function validateFormat(event) {\r\n        if" +
                        " (Page_ClientValidate()) {\r\n            $(\'#lblGrpError\').text(\' \');\r\n          " +
                        "  $(\'#lblRankError\').text(\' \');\r\n            var ext = $(\"input[name$=fuEventIma" +
                        "ge]\").get(0).files.length;\r\n            if (ext > 0) {\r\n                var name" +
                        "s = [];\r\n                for (var i = 0; i < ext; ++i) {\r\n                    na" +
                        "mes.push($(\"input[name$=fuEventImage]\").get(0).files[i].name);\r\n                " +
                        "}\r\n                var x = 0;\r\n                for (i = 0; i < names.length; i++" +
                        ") {\r\n                    var str = names[i];\r\n                    //  /^[-\\sa-zA" +
                        "-Z]+$/\r\n                    if (/^[-_a-zA-Z0-9.\\u0600-\\u06FF ]+$/.test(str) == f" +
                        "alse) {\r\n\r\n                        x = 1;\r\n                    }\r\n              " +
                        "      if (x == 1) {\r\n                        $(\'#lblImageError\').show();\r\n      " +
                        "                  $(\'#lblImageError\').text(\'Special characters except - and _ ar" +
                        "e not allowed in filename. Please select a valid image file of type .jpg,.jpeg,." +
                        "png.\');\r\n                        // setTimeout();\r\n                        retur" +
                        "n false;\r\n                        break;\r\n                        event.preventD" +
                        "efault();\r\n                    }\r\n\r\n                }\r\n                if (x == " +
                        "0) {\r\n\r\n                    var ext = [];\r\n                    for (i = 0; i < n" +
                        "ames.length; i++) {\r\n\r\n                        ext.push(names[i].substr(names[i]" +
                        ".indexOf(\".\") + 1).toLowerCase());\r\n\r\n                    }\r\n                   " +
                        " var valid_filetype = [\"jpg\", \"jpeg\", \"png\", \"PNG\", \"JPEG\", \"JPG\"];\r\n\r\n         " +
                        "           var i, j, result = [];\r\n                    for (i = 0; i < valid_fil" +
                        "etype.length; i++) {\r\n                        for (j = 0; j < ext.length; j++) {" +
                        "\r\n                            if (ext[j].indexOf(valid_filetype[i]) != -1) {\r\n  " +
                        "                              result.push(ext[j]);\r\n                            " +
                        "}\r\n                        }\r\n                    }\r\n\r\n                    if (r" +
                        "esult.length < ext.length) {\r\n                        //   break;\r\n             " +
                        "           $(\'#lblImageError\').show();\r\n                        $(\'#lblImageErro" +
                        "r\').text(\'Invalid File Found. Please select a valid image file of type .jpg,.jpe" +
                        "g,.png.\');\r\n                        // setTimeout();\r\n                        re" +
                        "turn false;\r\n                        event.preventDefault();\r\n                  " +
                        "  }\r\n\r\n\r\n\r\n                }\r\n\r\n            } else {\r\n               \r\n         " +
                        "   }\r\n\r\n        }\r\n    }\r\n\r\n</script>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
